### ISSUE TITLE
Add the ability to specify the fetchPolicy for the Query in the <ReactiveQuery> component

### ISSUE THREAD

**Issue by yellowspaceboots** [cult-of-coders/apollo-live-client#1]
I find that if I have fetched the query already and then close the subscription (navigate away from the page) and anything is changed while I am gone and then I come back the initial load will pull from the cache and be out of sync. I think that would be fixed just by changing the fetchPolicy to “cache-and-network” but I looked at your <ReactiveQuery> component and it looks like you’re only passing the query and variables to the react-apollo <Query> component.

**Comment by theodorDiaconu** [comment]
Published 0.2.1
